// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.21.12
// source: pkg/delay.proto

package pkg

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	DelayService_CreateDelay_FullMethodName = "/delay.DelayService/CreateDelay"
	DelayService_DeleteDelay_FullMethodName = "/delay.DelayService/DeleteDelay"
)

// DelayServiceClient is the client API for DelayService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DelayServiceClient interface {
	CreateDelay(ctx context.Context, in *CreateDelayRequest, opts ...grpc.CallOption) (*CreateDelayResponse, error)
	DeleteDelay(ctx context.Context, in *DeleteDelayRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type delayServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDelayServiceClient(cc grpc.ClientConnInterface) DelayServiceClient {
	return &delayServiceClient{cc}
}

func (c *delayServiceClient) CreateDelay(ctx context.Context, in *CreateDelayRequest, opts ...grpc.CallOption) (*CreateDelayResponse, error) {
	out := new(CreateDelayResponse)
	err := c.cc.Invoke(ctx, DelayService_CreateDelay_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *delayServiceClient) DeleteDelay(ctx context.Context, in *DeleteDelayRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, DelayService_DeleteDelay_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DelayServiceServer is the server API for DelayService service.
// All implementations must embed UnimplementedDelayServiceServer
// for forward compatibility
type DelayServiceServer interface {
	CreateDelay(context.Context, *CreateDelayRequest) (*CreateDelayResponse, error)
	DeleteDelay(context.Context, *DeleteDelayRequest) (*emptypb.Empty, error)
	mustEmbedUnimplementedDelayServiceServer()
}

// UnimplementedDelayServiceServer must be embedded to have forward compatible implementations.
type UnimplementedDelayServiceServer struct {
}

func (UnimplementedDelayServiceServer) CreateDelay(context.Context, *CreateDelayRequest) (*CreateDelayResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateDelay not implemented")
}
func (UnimplementedDelayServiceServer) DeleteDelay(context.Context, *DeleteDelayRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteDelay not implemented")
}
func (UnimplementedDelayServiceServer) mustEmbedUnimplementedDelayServiceServer() {}

// UnsafeDelayServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DelayServiceServer will
// result in compilation errors.
type UnsafeDelayServiceServer interface {
	mustEmbedUnimplementedDelayServiceServer()
}

func RegisterDelayServiceServer(s grpc.ServiceRegistrar, srv DelayServiceServer) {
	s.RegisterService(&DelayService_ServiceDesc, srv)
}

func _DelayService_CreateDelay_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateDelayRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DelayServiceServer).CreateDelay(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DelayService_CreateDelay_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DelayServiceServer).CreateDelay(ctx, req.(*CreateDelayRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DelayService_DeleteDelay_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteDelayRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DelayServiceServer).DeleteDelay(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DelayService_DeleteDelay_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DelayServiceServer).DeleteDelay(ctx, req.(*DeleteDelayRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DelayService_ServiceDesc is the grpc.ServiceDesc for DelayService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DelayService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "delay.DelayService",
	HandlerType: (*DelayServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateDelay",
			Handler:    _DelayService_CreateDelay_Handler,
		},
		{
			MethodName: "DeleteDelay",
			Handler:    _DelayService_DeleteDelay_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pkg/delay.proto",
}
