// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v3.21.12
// source: pkg/delay.proto

package pkg

import (
	reflect "reflect"
	sync "sync"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateDelayRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MessageId string `protobuf:"bytes,1,opt,name=messageId,proto3" json:"messageId,omitempty"`
	DateTime  int64  `protobuf:"varint,2,opt,name=dateTime,proto3" json:"dateTime,omitempty"`
}

func (x *CreateDelayRequest) Reset() {
	*x = CreateDelayRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_delay_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateDelayRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateDelayRequest) ProtoMessage() {}

func (x *CreateDelayRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_delay_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateDelayRequest.ProtoReflect.Descriptor instead.
func (*CreateDelayRequest) Descriptor() ([]byte, []int) {
	return file_pkg_delay_proto_rawDescGZIP(), []int{0}
}

func (x *CreateDelayRequest) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *CreateDelayRequest) GetDateTime() int64 {
	if x != nil {
		return x.DateTime
	}
	return 0
}

type CreateDelayResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Error     string `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	Id        string `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	MessageId string `protobuf:"bytes,3,opt,name=messageId,proto3" json:"messageId,omitempty"`
	DateTime  int64  `protobuf:"varint,4,opt,name=dateTime,proto3" json:"dateTime,omitempty"`
}

func (x *CreateDelayResponse) Reset() {
	*x = CreateDelayResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_delay_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateDelayResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateDelayResponse) ProtoMessage() {}

func (x *CreateDelayResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_delay_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateDelayResponse.ProtoReflect.Descriptor instead.
func (*CreateDelayResponse) Descriptor() ([]byte, []int) {
	return file_pkg_delay_proto_rawDescGZIP(), []int{1}
}

func (x *CreateDelayResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *CreateDelayResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CreateDelayResponse) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *CreateDelayResponse) GetDateTime() int64 {
	if x != nil {
		return x.DateTime
	}
	return 0
}

type DeleteDelayRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *DeleteDelayRequest) Reset() {
	*x = DeleteDelayRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_delay_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteDelayRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteDelayRequest) ProtoMessage() {}

func (x *DeleteDelayRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_delay_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteDelayRequest.ProtoReflect.Descriptor instead.
func (*DeleteDelayRequest) Descriptor() ([]byte, []int) {
	return file_pkg_delay_proto_rawDescGZIP(), []int{2}
}

func (x *DeleteDelayRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteDelayResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Error string `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *DeleteDelayResponse) Reset() {
	*x = DeleteDelayResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_delay_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteDelayResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteDelayResponse) ProtoMessage() {}

func (x *DeleteDelayResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_delay_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteDelayResponse.ProtoReflect.Descriptor instead.
func (*DeleteDelayResponse) Descriptor() ([]byte, []int) {
	return file_pkg_delay_proto_rawDescGZIP(), []int{3}
}

func (x *DeleteDelayResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_pkg_delay_proto protoreflect.FileDescriptor

var file_pkg_delay_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x70, 0x6b, 0x67, 0x2f, 0x64, 0x65, 0x6c, 0x61, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x05, 0x64, 0x65, 0x6c, 0x61, 0x79, 0x22, 0x4e, 0x0a, 0x12, 0x43, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x44, 0x65, 0x6c, 0x61, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1c,
	0x0a, 0x09, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x09, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x49, 0x64, 0x12, 0x1a, 0x0a, 0x08,
	0x64, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08,
	0x64, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x22, 0x75, 0x0a, 0x13, 0x43, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x44, 0x65, 0x6c, 0x61, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x14, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x65, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x49, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x49, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x64, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x64, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x22,
	0x24, 0x0a, 0x12, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x44, 0x65, 0x6c, 0x61, 0x79, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x2b, 0x0a, 0x13, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x44,
	0x65, 0x6c, 0x61, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x14, 0x0a, 0x05,
	0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x72, 0x72,
	0x6f, 0x72, 0x32, 0xa1, 0x01, 0x0a, 0x0f, 0x44, 0x65, 0x6c, 0x61, 0x79, 0x43, 0x6f, 0x6e, 0x74,
	0x72, 0x6f, 0x6c, 0x6c, 0x65, 0x72, 0x12, 0x46, 0x0a, 0x0b, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x44, 0x65, 0x6c, 0x61, 0x79, 0x12, 0x19, 0x2e, 0x64, 0x65, 0x6c, 0x61, 0x79, 0x2e, 0x43, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x44, 0x65, 0x6c, 0x61, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x1a, 0x2e, 0x64, 0x65, 0x6c, 0x61, 0x79, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x44,
	0x65, 0x6c, 0x61, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x46,
	0x0a, 0x0b, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x44, 0x65, 0x6c, 0x61, 0x79, 0x12, 0x19, 0x2e,
	0x64, 0x65, 0x6c, 0x61, 0x79, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x44, 0x65, 0x6c, 0x61,
	0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a, 0x2e, 0x64, 0x65, 0x6c, 0x61, 0x79,
	0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x44, 0x65, 0x6c, 0x61, 0x79, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x26, 0x5a, 0x24, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62,
	0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x4c, 0x69, 0x61, 0x72, 0x32, 0x33, 0x33, 0x2f, 0x63, 0x72, 0x6f,
	0x6e, 0x6f, 0x73, 0x2d, 0x73, 0x68, 0x6f, 0x76, 0x65, 0x6c, 0x2f, 0x70, 0x6b, 0x67, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pkg_delay_proto_rawDescOnce sync.Once
	file_pkg_delay_proto_rawDescData = file_pkg_delay_proto_rawDesc
)

func file_pkg_delay_proto_rawDescGZIP() []byte {
	file_pkg_delay_proto_rawDescOnce.Do(func() {
		file_pkg_delay_proto_rawDescData = protoimpl.X.CompressGZIP(file_pkg_delay_proto_rawDescData)
	})
	return file_pkg_delay_proto_rawDescData
}

var file_pkg_delay_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_pkg_delay_proto_goTypes = []interface{}{
	(*CreateDelayRequest)(nil),  // 0: delay.CreateDelayRequest
	(*CreateDelayResponse)(nil), // 1: delay.CreateDelayResponse
	(*DeleteDelayRequest)(nil),  // 2: delay.DeleteDelayRequest
	(*DeleteDelayResponse)(nil), // 3: delay.DeleteDelayResponse
}
var file_pkg_delay_proto_depIdxs = []int32{
	0, // 0: delay.DelayController.CreateDelay:input_type -> delay.CreateDelayRequest
	2, // 1: delay.DelayController.DeleteDelay:input_type -> delay.DeleteDelayRequest
	1, // 2: delay.DelayController.CreateDelay:output_type -> delay.CreateDelayResponse
	3, // 3: delay.DelayController.DeleteDelay:output_type -> delay.DeleteDelayResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pkg_delay_proto_init() }
func file_pkg_delay_proto_init() {
	if File_pkg_delay_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pkg_delay_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateDelayRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_delay_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateDelayResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_delay_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteDelayRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_delay_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteDelayResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pkg_delay_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_delay_proto_goTypes,
		DependencyIndexes: file_pkg_delay_proto_depIdxs,
		MessageInfos:      file_pkg_delay_proto_msgTypes,
	}.Build()
	File_pkg_delay_proto = out.File
	file_pkg_delay_proto_rawDesc = nil
	file_pkg_delay_proto_goTypes = nil
	file_pkg_delay_proto_depIdxs = nil
}
